---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - t3_proxy
    ports:
      - 6767:6767
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ../data/bazarr/config:/config
      - ${MOVIES_PATH}:/movies
      - ${ANIME_PATH}:/anime
      - ${TV_PATH}:/tv
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr-rtr.rule=Host(`bazarr.${DOMAIN}`)"
      - "traefik.http.routers.bazarr-rtr.entrypoints=https"
      - "traefik.http.routers.bazarr-rtr.tls=true"
      - "traefik.http.routers.bazarr-rtr.tls.certresolver=dns-route53"
      - "traefik.http.routers.bazarr-rtr.middlewares=authentik@docker"
      