services:  
# Prowlarr - Torrent proxy
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - t3_proxy
    ports:
      - 9696:9696
    volumes:
      - ../data/prowlarr/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr-rtr.rule=Host(`prowlarr.${DOMAIN}`)"
      - "traefik.http.routers.prowlarr-rtr.entrypoints=https"
      - "traefik.http.routers.prowlarr-rtr.tls=true"
      - "traefik.http.routers.prowlarr-rtr.tls.certresolver=dns-route53"
      - "traefik.http.routers.prowlarr-rtr.middlewares=authentik@docker"
      