services:
  # WhoAmI - For Testing and Troubleshooting
  whoami:
    image: traefik/whoami:v1.11
    container_name: whoami
    profiles: ["debug"]
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-rtr.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami-rtr.entrypoints=https"
      - "traefik.http.routers.whoami-rtr.tls=true"
      - "traefik.http.routers.whoami-rtr.tls.certresolver=dns-route53"
      - "traefik.http.routers.whoami-rtr.middlewares=authentik@docker"
